# Generated by Django 4.0.4 on 2022-05-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_clientes',
            name='numero_celular',
            field=models.CharField(max_length=11),
        ),
    ]
